title: vincent
email: vh7157@gmail.com
description: >-
  Thoughts around programming and life

baseurl: ""
url: "https://vincent178.github.io"

# twitter_username: jekyllrb
# github_username:  jekyll

theme: no-style-please

theme_config:
  appearance: "auto"
  back_home_text: ".."
  date_format: "%Y-%m-%d"
  show_description: false

plugins:
  - jekyll-feed

# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
